spring.application.name=BidEk
# MongoDB Configuration
spring.data.mongodb.database=bidekdb
spring.data.mongodb.port=27017
spring.data.mongodb.host=localhost

# Spring Security
spring.security.user.name=admin
spring.security.user.password=admin123
server.port=9090

logging.level.org.springframework.security=DEBUG
